apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletin-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bulletin
  template:
    metadata:
      labels:
        app: bulletin
    spec:
      containers:
        - name: example
          image: bulletinboard:1.0
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP