apiVersion: batch/v1
kind: Job
metadata:
  name: pi-5
spec:
  ttlSecondsAfterFinished: 20
  template:
    spec:
      containers:
      - name: phases
        image: success:1.0
      restartPolicy: Never
  backoffLimit: 4