apiVersion: v1
kind: Pod
metadata:
  name: pvc-example
spec:
  containers:
  - image: alpine:latest
    name: bb
    command:
    - sleep
    - "10000"
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: test-volume
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: mypvc