apiVersion: v1
kind: PersistentVolume
metadata:
  name: some-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/local-path-provisioner/some-pv
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kind-control-plane
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem