apiVersion: v1
kind: Pod
metadata:
  name: app-redis
spec:
  containers:
    - name: web
      image: web:1.0
      env:
      - name: REDIS_URL
        value: "localhost"
      ports:
        - name: web
          containerPort: 5000
          protocol: TCP
    - name: redis
      image: redis:alpine