apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: example
      image: bulletinboard:1.0
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP