apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: 
  - secrets
  resourceNames:
  - mysecret
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secret
subjects: # we can bind it to multiple subjects.
- kind: ServiceAccount
  name: muvaffak
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io