FROM maven:3.6.3-openjdk-16-slim as BUILD

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN mvn package

# Once we use FROM, it means we are at a different stage. 

FROM openjdk:16-jdk-alpine3.12
COPY --from=BUILD /usr/src/app/target/app.war .
CMD ["java", "-jar", "app.war"]