apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
spec:
  containers:
  - image: alpine:latest
    name: bb
    command:
    - sleep
    - "10000"
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /tmp/kind-cluster-host-data
      type: DirectoryOrCreate